# Generated by Django 3.1.6 on 2021-03-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_comment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
